In [ ]:
import os  # Provides a way to use operating system dependent functionality like reading or writing to the file system
import glob
import pickle
import pandas as pd  # Powerful data structures for data analysis, time series, and statistics
import numpy as np  # Support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays
from tqdm import tqdm  # For progress bars
from sklearn.metrics.pairwise import cosine_similarity  # Computes the cosine similarity between samples in a matrix

# For W2V specifically
import re  # Provides regular expression matching operations
import ast  # Abstract Syntax Trees, used for parsing and analyzing Python source code
from collections import Counter  # Provides a way to count the frequency of elements in a collection
import gensim  # Library for unsupervised topic modeling and natural language processing
import gensim.downloader as api  # Downloads and loads pre-trained models and datasets
# from gensim.models import KeyedVectors  # Provides efficient word vector representation and storage

#For BERT specifically 
import torch
from transformers import BertTokenizer, BertModel, AutoTokenizer, AutoModel
from huggingface_hub import login

bert_tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
bert_model = BertModel.from_pretrained("bert-base-uncased")


# Log in with your token
login("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")

# Set the Hugging Face token as an environment variable
#os.environ["HUGGINGFACE_TOKEN"] = "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"


llama_tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-3.2-1B-Instruct", use_auth_token=True)
llama_model = AutoModel.from_pretrained("meta-llama/Llama-3.2-1B-Instruct", torch_dtype=torch.float16, use_auth_token=True)

Exception ignored in: <bound method IPythonKernel._clean_thread_parent_frames of <ipykernel.ipkernel.IPythonKernel object at 0x0000016E39C65DB0>>
Traceback (most recent call last):
  File "d:\ASU\ALIGN\AlignCloneRepo\align-linguistic-alignment\src\align\semantic_alignment_venv\lib\site-packages\ipykernel\ipkernel.py", line 788, in _clean_thread_parent_frames
    if phase != "start":
KeyboardInterrupt:
d:\ASU\ALIGN\AlignCloneRepo\align-linguistic-alignment\src\align\semantic_alignment_venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [ ]:
def pair_and_lag_columns(df: pd.DataFrame, columns_to_lag: list, suffix1: str = '1', suffix2: str = '2') -> pd.DataFrame:
    """
    Creates lagged pairs of specified columns, generating new columns with a 
    suffix of `suffix1` for the original content and `suffix2` for the lagged content. 
    Also adds a new column indicating the order of participants between successive rows.
    """
    for col in columns_to_lag:
        if col in df.columns:
            df[f'{col}{suffix1}'] = df[col]
            df[f'{col}{suffix2}'] = df[col].shift(-1)
    df['utter_order'] = df['participant'] + ' ' + df['participant'].shift(-1)
    return df

def calculate_cosine_similarity(df: pd.DataFrame, embedding_pairs: list) -> pd.DataFrame:
    """
    Computes cosine similarities between pairs of vectors in the specified columns 
    and adds the results as new columns in the DataFrame.
    """
    for col1, col2 in embedding_pairs:
        similarities = df.apply(
            lambda row: cosine_similarity(
                np.array(row[col1]).reshape(1, -1),
                np.array(row[col2]).reshape(1, -1)
            )[0][0] if row[col1] is not None and row[col2] is not None else None,
            axis=1
        )
        similarity_column_name = f"{col1}_{col2}_cosine_similarity"
        df[similarity_column_name] = similarities
    return df

# BEGIN WORD2VEC

#### Steps: Load in models → Aggregate conversations → Build vocabulary → Pair and lag columns → Compute embeddings → Compute cosine similarities.

### SETUP for W2V

In [ ]:
# # retrieve the curent working directory where the script is being executed
# script_dir = os.getcwd()

# # create a directory called "gensim-data" (if doesn't already exist)
# local_cache_dir = os.path.join(script_dir, "gensim-data")
# os.makedirs(local_cache_dir, exist_ok=True)
# print(f"Local cache directory: {local_cache_dir}")

# # configure Gensim to use local_cache_dir as base directory for downloading and storing models
# api.BASE_DIR = local_cache_dir
# print(f"Gensim BASE_DIR set to: {api.BASE_DIR}")

# checks if specified models are already downloaded to cache directory, if not, download them
def download_and_cache_models(models, cache_dir):
    api.BASE_DIR = cache_dir
    for model_name in models:
        model_path = os.path.join(cache_dir, model_name)
        if not os.path.exists(model_path):
            try:
                print(f"Downloading model: {model_name}")
                model = api.load(model_name)
                print(f"Downloaded and cached model: {model_name}")
            except Exception as e:
                print(f"Error downloading {model_name}: {e}")
        else:
            print(f"Model {model_name} already exists at: {model_path}")

# specifies the list of models to be cached locally, invoking the download_and_cache_models function 
# models_to_cache = ['word2vec-google-news-300', 'glove-twitter-200']
# download_and_cache_models(models_to_cache, local_cache_dir)

# attempts to load a model from specified file path
def load_model_if_not_exists(model_path, binary=True):
    try:
        if not os.path.exists(model_path):
            raise FileNotFoundError(f"Model file {model_path} does not exist.")
        return gensim.models.KeyedVectors.load_word2vec_format(model_path, binary=binary)
    except Exception as e:
        print(f"Error loading model from {model_path}: {e}")
        return None

# # checks if the w2v_google_model is already loaded in the global namespace. if not, attempts to load it from local cache directory.
# if 'w2v_google_model' not in globals():
#     w2v_google_model_path = os.path.join(local_cache_dir, 'word2vec-google-news-300', 'word2vec-google-news-300.gz')
#     w2v_google_model = load_model_if_not_exists(w2v_google_model_path, binary=True)
#     if w2v_google_model is not None:
#         print("Word2Vec Google News model loaded from local cache successfully.")
#     else:
#         print("Failed to load Word2Vec Google News model.")

# note: possible todo: is it more efficient to use gensim.downloader.load(model_name)?
# note, downloading model, it downloads properly, but also throws the exception warning for some reason. 
# TODO: instead of just loading google news model into global workspace, load in all within "models_to_cache"

### Aggregate conversations → Build vocabulary

In [ ]:
def aggregate_conversations(folder_path: str) -> pd.DataFrame:
    """
    Aggregates multiple .txt files located in a specified folder 
    into a single pandas DataFrame. Each file is expected to be 
    tab-separated. 
    
    Returns a DataFrame containing the concatenated content of all 
    the .txt files
    """
    text_files = [f for f in os.listdir(folder_path) if os.path.isfile(os.path.join(folder_path, f)) and f.endswith('.txt')]
    concatenated_df = pd.DataFrame()

    for file_name in text_files:
        file_path = os.path.join(folder_path, file_name)
        df = pd.read_csv(file_path, sep='\t', encoding='utf-8')
        concatenated_df = pd.concat([concatenated_df, df], ignore_index=True)
    
    return concatenated_df

def build_filtered_vocab(data: pd.DataFrame, output_file_directory: str, high_sd_cutoff: float = 3, low_n_cutoff: int = 1):
    """
    Constructs a vocabulary from the ‘lemma’ column of the input DataFrame, 
    applying frequency-based filtering: ords occurring less frequently 
    than low_n_cutoff or more frequently than a certain standard deviation 
    above the mean (high_sd_cutoff) are filtered out. 
    
    Returns: Two lists: one with all vocabulary words and another with filtered words
    Outputs: The vocabulary frequencies to files
    """ 

    all_sentences = [re.sub(r'[^\w\s]+', '', str(row)).split() for row in data['lemma']]
    all_words = [word for sentence in all_sentences for word in sentence]

    frequency = Counter(all_words)

    frequency_filt = {word: freq for word, freq in frequency.items() if len(word) > 1 and freq > low_n_cutoff}
    
    if high_sd_cutoff is not None:
        mean_freq = np.mean(list(frequency_filt.values()))
        std_freq = np.std(list(frequency_filt.values()))
        cutoff_freq = mean_freq + (std_freq * high_sd_cutoff)
        filteredWords = {word: freq for word, freq in frequency_filt.items() if freq < cutoff_freq}
    else:
        filteredWords = frequency_filt
  
    vocabfreq_all = pd.DataFrame(frequency.items(), columns=["word", "count"]).sort_values(by='count', ascending=False)
    vocabfreq_filt = pd.DataFrame(filteredWords.items(), columns=["word", "count"]).sort_values(by='count', ascending=False)
  
    vocabfreq_all.to_csv(os.path.join(output_file_directory, 'vocab_unfilt_freqs.txt'), encoding='utf-8', index=False, sep='\t')
    vocabfreq_filt.to_csv(os.path.join(output_file_directory, 'vocab_filt_freqs.txt'), encoding='utf-8', index=False, sep='\t')
    
    return list(frequency.keys()), list(filteredWords.keys())

def is_list_like_column(series):
    """
    Checks if a pandas Series contains list-like strings (i.e., strings that 
    look like lists).
    """    

    try:
        return series.apply(lambda x: x.strip().startswith("[")).all()
    except AttributeError:
        return False

def convert_columns_to_lists(df: pd.DataFrame) -> pd.DataFrame:
    """
    Converts any columns in a DataFrame that contain list-like strings into 
    actual Python lists using ast.literal_eval.
    """        

    columns_converted = []
    for col in df.columns:
        if is_list_like_column(df[col]):
            df[col] = df[col].apply(ast.literal_eval)
            columns_converted.append(col)
    return df, columns_converted

### Pair and lag columns → Compute embeddings → Compute cosine similarities.

In [ ]:
def get_sum_embeddings(token_list, model):
    """
    Calculates the sum of word embeddings for a list of tokens using a 
    pre-trained Word2Vec model.
    """ 

    if token_list is None:
        return None    
    embeddings = []
    for word in token_list:
        if word in model.key_to_index:  
            embeddings.append(model[word])    
    if embeddings:
        sum_embedding = np.sum(embeddings, axis=0)
        return sum_embedding
    else:
        return None  
    
def process_file_for_W2V(file_path, vocab_list: list,w2v_google_model):
    """
    Processes a file containing conversation data, filters tokens based on a provided vocabulary list,
    pairs and lags columns, computes word embeddings, and then calculates cosine similarities 
    between the embeddings.
    """
    df = pd.read_csv(file_path, sep='\t', encoding='utf-8')

    df, columns_converted = convert_columns_to_lists(df)

    # Filter tokens based on the vocabulary list
    columns_to_filter = ['lemma', 'token']
    for col in columns_to_filter:
        df[col] = df[col].apply(lambda token_list: [word for word in token_list if word in vocab_list])

    # Pair and lag the columns
    columns_to_lag = ['content', 'token', 'lemma']
    df = pair_and_lag_columns(df, columns_to_lag)

    # Compute embeddings
    for column in ["lemma", "token"]:
        df[f"{column}1_sum_embedding"] = df[f"{column}1"].apply(lambda tokens: get_sum_embeddings(tokens, w2v_google_model))
        df[f"{column}2_sum_embedding"] = df[f"{column}2"].apply(lambda tokens: get_sum_embeddings(tokens, w2v_google_model))

    # Calculate cosine similarities
    embedding_columns = [
        ("lemma1_sum_embedding_W2V", "lemma2_sum_embedding_W2V"),
        ("token1_sum_embedding_W2V", "token2_sum_embedding_W2V")
    ]
    df = calculate_cosine_similarity(df, embedding_columns)

    return df

# END WORD2VEC

# BEGIN BERT AND LLAMA

#### Steps: Pair and lag columns → Compute embeddings → Compute cosine similarities.

In [ ]:
def get_embedding_with_cache(text, embedding_cache, tokenizer,model):
    """
    Generates a BERT embedding for a given text while utilizing a cache to avoid redundant computations:
	•	  Checks if the embedding for the given text is already in the cache. If so, returns it.
	•	  If not cached, tokenizes the text, converts tokens to IDs, and feeds them to the BERT model to get the embedding.
	•	  The embedding is then averaged over all tokens and stored in the cache for future use.
    """ 
    
    if text is None:
      return None

    if text in embedding_cache:
      return embedding_cache[text]

    tokens = tokenizer.tokenize(text)
    token_ids = tokenizer.convert_tokens_to_ids(tokens)
    
    if not token_ids:
        print(f"Warning: No valid tokens generated for text: '{text}'")
        return None  # Or handle with a default embedding
    token_ids = [tokenizer.cls_token_id] + token_ids + [tokenizer.sep_token_id]
    token_ids = [token for token in token_ids if token is not None]

    #print(text, token_ids)
    # if not token_ids:
    #   print(2)
    #   print(f"Tokenization failed for text: '{text}'")
    #   return None
    #print(3)
    input_ids = torch.tensor([token_ids])
    #print(4)
    with torch.no_grad():
        outputs = model(input_ids)
    last_hidden_states = outputs.last_hidden_state
    embedding = torch.mean(last_hidden_states, dim=1).numpy()
    if embedding is None or embedding.size == 0:
        print(f"Error: Empty embedding for text: '{text}'")
        return None
    embedding_cache[text] = embedding

    return embedding

def process_file(file_path, embedding_cache, tokenizer, model, model_name):
    """
    Processes a single file to compute embeddings for pairs of utterances and 
    calculates the cosine similarity between these embeddings:
    • Reads the file into a DataFrame.
    • Pairs and lags the `content` column using `pair_and_lag_columns`.
    • Applies the `get_embedding_with_cache` function to each utterance pair 
      to compute embeddings.
    • Computes the cosine similarity between embeddings of successive utterances.
    """

    df = pd.read_csv(file_path, sep='\t', encoding='utf-8')

    # Pair and lag the columns
    df = pair_and_lag_columns(df, columns_to_lag=['content'])

    # Compute embeddings for the lagged columns with model-specific suffixes
    for column in ["content1", "content2"]:
        df[f"{column}_embedding_{model_name}"] = df[column].apply(
            lambda text: get_embedding_with_cache(text, embedding_cache, tokenizer, model)
        )

    # Calculate cosine similarities between embeddings with the model name
    embedding_columns = [(f"content1_embedding_{model_name}", f"content2_embedding_{model_name}")]
    df = calculate_cosine_similarity(df, embedding_columns)

    return df

### Main Run

In [ ]:
def semantic_alignment(
    folder_path,
    output_file_directory,
    BERT_embedding_cache_path,
    Llama_embedding_cache_path,
    use_W2V=True,
    use_BERT=True,
    use_Llama=True
):
    # Prepare W2V processing if use_W2V is True
    concatenated_df1 = pd.DataFrame()
    if use_W2V:
        # Set up local cache for Gensim and load W2V model
        script_dir = os.getcwd()
        local_cache_dir = os.path.join(script_dir, "gensim-data")
        os.makedirs(local_cache_dir, exist_ok=True)
        print(f"Local cache directory: {local_cache_dir}")

        # Configure Gensim to use the local cache directory
        api.BASE_DIR = local_cache_dir
        models_to_cache = ['word2vec-google-news-300', 'glove-twitter-200']
        download_and_cache_models(models_to_cache, local_cache_dir)

        # Load Word2Vec Google News model
        if 'w2v_google_model' not in globals():
            w2v_google_model_path = os.path.join(local_cache_dir, 'word2vec-google-news-300', 'word2vec-google-news-300.gz')
            w2v_google_model = load_model_if_not_exists(w2v_google_model_path, binary=True)
            if w2v_google_model:
                print("Word2Vec Google News model loaded successfully.")
            else:
                print("Failed to load Word2Vec Google News model.")

        # Process files with Word2Vec
        os.makedirs(output_file_directory, exist_ok=True)
        text_files = [f for f in os.listdir(folder_path) if f.endswith('.txt')]
        concatenated_text_files = aggregate_conversations(folder_path)
        vocab_all, vocab_filtered = build_filtered_vocab(concatenated_text_files, output_file_directory)
        for file_name in tqdm(text_files, desc="Processing files for W2V"):
            file_path = os.path.join(folder_path, file_name)
            df = process_file_for_W2V(file_path, vocab_filtered, w2v_google_model)
            concatenated_df1 = pd.concat([concatenated_df1, df], ignore_index=True)
    
    # Prepare BERT processing if use_BERT is True
    concatenated_df2 = pd.DataFrame()
    if use_BERT:
        # Load or initialize BERT embedding cache
        try:
            with open(BERT_embedding_cache_path, "rb") as f:
                embedding_cache = pickle.load(f)
        except FileNotFoundError:
            embedding_cache = {}

        # Process files with BERT
        text_files = [f for f in os.listdir(folder_path) if f.endswith('.txt')]
        for file_name in tqdm(text_files, desc="Processing files for BERT"):
            file_path = os.path.join(folder_path, file_name)
            df = process_file(file_path, embedding_cache, bert_tokenizer, bert_model,model_name="BERT")
            concatenated_df2 = pd.concat([concatenated_df2, df], ignore_index=True)

        # Save updated BERT embedding cache
        with open(BERT_embedding_cache_path, "wb") as embedding_cache_file:
            pickle.dump(embedding_cache, embedding_cache_file)

    # Prepare Llama processing if use_Llama is True
    concatenated_df3 = pd.DataFrame()
    if use_Llama:
        # Load or initialize Llama embedding cache
        try:
            with open(Llama_embedding_cache_path, "rb") as f:
                print("Hii")
                embedding_cache = pickle.load(f)
        except FileNotFoundError:
            embedding_cache = {}
            print("Hello")

        # Process files with Llama
        text_files = [f for f in os.listdir(folder_path) if f.endswith('.txt')]
        for file_name in tqdm(text_files, desc="Processing files for Llama"):
            file_path = os.path.join(folder_path, file_name)
            df = process_file(file_path, embedding_cache, llama_tokenizer, llama_model,model_name="Llama")
            concatenated_df3 = pd.concat([concatenated_df3, df], ignore_index=True)

        # Save updated Llama embedding cache
        with open(Llama_embedding_cache_path, "wb") as embedding_cache_file:
            pickle.dump(embedding_cache, embedding_cache_file)

    # Combine results based on which embeddings are enabled
    result_df = pd.DataFrame()
    if use_W2V:
        result_df = concatenated_df1
    if use_BERT:
        result_df = pd.concat([result_df, concatenated_df2], axis=1, join="inner")
    if use_Llama:
        result_df = pd.concat([result_df, concatenated_df3], axis=1, join="inner")

    return result_df, concatenated_df1, concatenated_df2, concatenated_df3

In [ ]:
# Define folder paths
folder_path = "D:\ASU\ALIGN\data_for_update_MERGED"
output_file_directory = "outputW2V"
# Attempts to load a pre-existing embedding cache from a file (bert_embedding_cache.pkl).
BERT_embedding_cache_path = "D:\\ASU\\ALIGN\\data_for_update_MERGED\\bert_embedding_cache.pkl"
Llama_embedding_cache_path = "D:\\ASU\\ALIGN\\data_for_update_MERGED\\llama_embedding_cache.pkl"
result_df, df1, df2, df3 = semantic_alignment(folder_path, 
                                         output_file_directory, 
                                         BERT_embedding_cache_path, 
                                         Llama_embedding_cache_path, 
                                         use_W2V = True, 
                                         use_BERT=True,
                                         use_Llama=True)

Hello

Processing files for LLaMa:   0%|          | 0/2 [00:00<?, ?it/s]

yeah let's try that one [76515, 1095, 596, 1456, 430, 832]
this one [576, 832]
yeah that one doesn't look too bad [76515, 430, 832, 3250, 956, 1427, 2288, 3958]
dropped something [11513, 7069, 2555]
i feel like that's the solution to all of these [72, 2733, 1093, 430, 596, 279, 6425, 311, 682, 315, 1521]
 boy yeah just make a thing like a weight like last time [8334, 22371, 1120, 1304, 264, 3245, 1093, 264, 4785, 1093, 1566, 892]
yeah how is this any different from last time [76515, 1268, 374, 420, 904, 2204, 505, 1566, 892]
don't know [15357, 956, 1440]
k wait now try and delete the red thing and see if it just flies back down [74, 3868, 1457, 1456, 323, 3783, 279, 2579, 3245, 323, 1518, 422, 433, 1120, 38204, 1203, 1523]
i think it needs to swing out to the right side while it's like going up or down [72, 1781, 433, 3966, 311, 19336, 704, 311, 279, 1314, 3185, 1418, 433, 596, 1093, 2133, 709, 477, 1523]
yeah but i think it might have gotten stuck now [76515, 719, 602, 1781, 433, 2643, 617, 17454, 16075, 1457]
 if you hit the space bar i think it restarts it [422, 499, 4295, 279, 3634, 3703, 602, 1781, 433, 17460, 82, 433]
 we got a gold one [584, 2751, 264, 6761, 832]
sweet come on [95928, 2586, 389]
i don't know what that means but gold is good [72, 1541, 956, 1440, 1148, 430, 3445, 719, 6761, 374, 1695]

Processing files for LLaMa:  50%|█████     | 1/2 [03:09<03:09, 189.13s/it]

i thought that maybe that would do something [72, 3463, 430, 7344, 430, 1053, 656, 2555]
i think you have to c maybe close it and it will work you didn't close the circle all the way [72, 1781, 499, 617, 311, 272, 7344, 3345, 433, 323, 433, 690, 990, 499, 3287, 956, 3345, 279, 12960, 682, 279, 1648]
should i restart this it's like down there [5562, 602, 17460, 420, 433, 596, 1093, 1523, 1070]
yeah i would just restart it [76515, 602, 1053, 1120, 17460, 433]
okay now what   [94317, 1457, 1148, 256]
you didn't close it [9514, 3287, 956, 3345, 433]
yeah but what does it matter if i close it [76515, 719, 1148, 1587, 433, 5030, 422, 602, 3345, 433]
 we could make another pendulum and it could swing up to it [584, 1436, 1304, 2500, 42630, 16903, 323, 433, 1436, 19336, 709, 311, 433]
okay okay [94317, 17339]
you're gonna have to swing up somehow [9514, 2351, 16926, 617, 311, 19336, 709, 17354]
 well i don't really know how we're gonna get it to swing regardless though   'cause it's gonna be heavy [1664, 602, 1541, 956, 2216, 1440, 1268, 584, 2351, 16926, 636, 433, 311, 19336, 15851, 3582, 256, 364, 1593, 433, 596, 16926, 387, 8987]
maybe pin it to like that blue wave [37860, 9160, 433, 311, 1093, 430, 6437, 12330]
no the blue wave underneath the balloon [2201, 279, 6437, 12330, 30456, 279, 47856]
 well there is a blue wave or i mean there is a pin on the blue wave [1664, 1070, 374, 264, 6437, 12330, 477, 602, 3152, 1070, 374, 264, 9160, 389, 279, 6437, 12330]
it's not attached to it though [275, 596, 539, 12673, 311, 433, 3582]
yeah it is look this one [76515, 433, 374, 1427, 420, 832]
it's on my screen it's not attached to the blob [275, 596, 389, 856, 4264, 433, 596, 539, 12673, 311, 279, 24295]
okay i think you need to rephrase what you're trying to say [94317, 602, 1781, 499, 1205, 311, 312, 28810, 1148, 499, 2351, 4560, 311, 2019]
pin the blob to the blue wave [13576, 279, 24295, 311, 279, 6437, 12330]
this i don't think i can retroactively attach a pin like i don't think it's gonna do anything [576, 602, 1541, 956, 1781, 602, 649, 17189, 64119, 15866, 264, 9160, 1093, 602, 1541, 956, 1781, 433, 596, 16926, 656, 4205]
well we need to get it to swing so [9336, 584, 1205, 311, 636, 433, 311, 19336, 779]
now we have our ball at least [3409, 584, 617, 1057, 5041, 520, 3325]
drop something heavy catapult it [6861, 2555, 8987, 96191, 433]
there we go [19041, 584, 733]
   no   okay now that he's over there okay what if we do i don't really know what to do [256, 912, 256, 17339, 1457, 430, 568, 596, 927, 1070, 17339, 1148, 422, 584, 656, 602, 1541, 956, 2216, 1440, 1148, 311, 656]
i would [72, 1053]
got me [23196, 757]
i would just try and draw something drop something really really really heavy [72, 1053, 1120, 1456, 323, 4128, 2555, 6068, 2555, 2216, 2216, 2216, 8987]
the thing is there's no like fulcrum for it to   rotate on [1820, 3245, 374, 1070, 596, 912, 1093, 5716, 5192, 372, 369, 433, 311, 256, 17348, 389]
right make like a teaspoon type s [1315, 1304, 1093, 264, 42384, 955, 274]
on the on the brown like that  like like like i understand what you're saying [263, 279, 389, 279, 14198, 1093, 430, 220, 1093, 1093, 1093, 602, 3619, 1148, 499, 2351, 5605]
yeah and then drop it [76515, 323, 1243, 6068, 433]
   it's gonna have to be a big   okay just kidding [256, 433, 596, 16926, 617, 311, 387, 264, 2466, 256, 17339, 1120, 56825]
wonder if you can move the balloon you drop something like on the balloon and make it move [86, 14518, 422, 499, 649, 3351, 279, 47856, 499, 6068, 2555, 1093, 389, 279, 47856, 323, 1304, 433, 3351]
 we can try that [584, 649, 1456, 430]
 maybe never tried that before [7344, 2646, 6818, 430, 1603]
that was like almost good okay let's [9210, 574, 1093, 4661, 1695, 17339, 1095, 596]
draw something [7788, 2555]
aw aw [675, 1384]
balloon can not be touched [13616, 32435, 649, 539, 387, 24891]
maybe if we just go heavier and higher  okay that's not really what i wanted but  [37860, 422, 584, 1120, 733, 44922, 323, 5190, 220, 17339, 430, 596, 539, 2216, 1148, 602, 4934, 719, 220]
maybe they did dolphins because you know how dolphins like bounce balls to each other maybe we're supposed to bounce it from like one dolphin to another and then get to the balloon [37860, 814, 1550, 83506, 1606, 499, 1440, 1268, 83506, 1093, 34782, 20953, 311, 1855, 1023, 7344, 584, 2351, 10171, 311, 34782, 433, 505, 1093, 832, 99269, 311, 2500, 323, 1243, 636, 311, 279, 47856]
how would we even do that [5269, 1053, 584, 1524, 656, 430]
like from [4908, 505]
 i think we'll have to make platforms or something [602, 1781, 584, 3358, 617, 311, 1304, 15771, 477, 2555]
the bottom one to the left one i don't know yeah something like that [1820, 5740, 832, 311, 279, 2163, 832, 602, 1541, 956, 1440, 22371, 2555, 1093, 430]
okay those would not connect to each other wait but even if we did that [94317, 1884, 1053, 539, 4667, 311, 1855, 1023, 3868, 719, 1524, 422, 584, 1550, 430]
that might be okay and then if we could jump if we made another thing like that if we could jump it up to the next one [9210, 2643, 387, 17339, 323, 1243, 422, 584, 1436, 7940, 422, 584, 1903, 2500, 3245, 1093, 430, 422, 584, 1436, 7940, 433, 709, 311, 279, 1828, 832]
okay so  [94317, 779, 220]

Processing files for LLaMa: 100%|██████████| 2/2 [14:38<00:00, 439.34s/it]

In [ ]:
df1.head()

Empty DataFrame
Columns: []
Index: []

In [ ]:
df2.head()

Empty DataFrame
Columns: []
Index: []

In [ ]:
df3.head()

,participant,content,token,lemma,tagged_token,tagged_lemma,tagged_stan_token,tagged_stan_lemma,file,content1,content2,utter_order,content1_embedding,content2_embedding,content1_embedding_content2_embedding_cosine_similarity
0,PC:,yeah let's try that one,"['yeah', 'let', 'us', 'try', 'that', 'one']","['yeah', 'let', 'u', 'try', 'that', 'one']","[('yeah', 'NN'), ('let', 'VBD'), ('us', 'PRP')...","[('yeah', 'NNS'), ('let', 'VBP'), ('u', 'JJ'),...","[('yeah', 'JJ'), ('let', 'VB'), ('us', 'PRP'),...","[('yeah', 'JJ'), ('let', 'VB'), ('u', 'FW'), (...",ASU-T10_ExpBlock1-Oneatatime.txt,yeah let's try that one,this one,PC: PB:,"[[0.7837, 2.96, 1.602, -0.276, 1.426, -2.156, ...","[[0.745, 1.303, 2.146, -0.08435, 2.545, -0.989...",0.766587
1,PB:,this one,"['this', 'one']","['this', 'one']","[('this', 'DT'), ('one', 'NN')]","[('this', 'DT'), ('one', 'NN')]","[('this', 'DT'), ('one', 'CD')]","[('this', 'DT'), ('one', 'CD')]",ASU-T10_ExpBlock1-Oneatatime.txt,this one,yeah that one doesn't look too bad,PB: PA:,"[[0.745, 1.303, 2.146, -0.08435, 2.545, -0.989...","[[-0.005745, 2.496, 0.9585, -0.2312, 2.066, -0...",0.807092
2,PA:,yeah that one doesn't look too bad,"['yeah', 'that', 'one', 'does', 'not', 'look',...","['yeah', 'that', 'one', 'do', 'not', 'look', '...","[('yeah', 'NN'), ('that', 'WDT'), ('one', 'CD'...","[('yeah', 'NN'), ('that', 'WDT'), ('one', 'CD'...","[('yeah', 'NN'), ('that', 'IN'), ('one', 'CD')...","[('yeah', 'NN'), ('that', 'IN'), ('one', 'CD')...",ASU-T10_ExpBlock1-Oneatatime.txt,yeah that one doesn't look too bad,dropped something,PA: PB:,"[[-0.005745, 2.496, 0.9585, -0.2312, 2.066, -0...","[[-0.1786, 2.557, 2.37, -1.125, 1.802, 0.1137,...",0.817660
3,PB:,dropped something,"['dropped', 'something']","['drop', 'something']","[('dropped', 'VBD'), ('something', 'NN')]","[('drop', 'NN'), ('something', 'NN')]","[('dropped', 'VBD'), ('something', 'NN')]","[('drop', 'NN'), ('something', 'NN')]",ASU-T10_ExpBlock1-Oneatatime.txt,dropped something,i feel like that's the solution to all of these,PB: PA:,"[[-0.1786, 2.557, 2.37, -1.125, 1.802, 0.1137,...","[[0.2268, 2.648, 1.566, -0.841, 2.049, -1.122,...",0.773216
4,PA:,i feel like that's the solution to all of these,"['i', 'feel', 'like', 'that', 'is', 'the', 'so...","['i', 'feel', 'like', 'that', 'be', 'the', 'so...","[('i', 'JJ'), ('feel', 'VBP'), ('like', 'IN'),...","[('i', 'JJ'), ('feel', 'VBP'), ('like', 'IN'),...","[('i', 'LS'), ('feel', 'VB'), ('like', 'IN'), ...","[('i', 'LS'), ('feel', 'VB'), ('like', 'IN'), ...",ASU-T10_ExpBlock1-Oneatatime.txt,i feel like that's the solution to all of these,boy yeah just make a thing like a weight like...,PA: PB:,"[[0.2268, 2.648, 1.566, -0.841, 2.049, -1.122,...","[[0.866, 3.41, 1.314, -0.641, 1.87, -2.512, 2....",0.824969

In [ ]:
result_df.head()

,participant,content,token,lemma,tagged_token,tagged_lemma,tagged_stan_token,tagged_stan_lemma,file,content1,...,utter_order,lemma1_sum_embedding,lemma2_sum_embedding,token1_sum_embedding,token2_sum_embedding,lemma1_sum_embedding_lemma2_sum_embedding_cosine_similarity,token1_sum_embedding_token2_sum_embedding_cosine_similarity,content1_embedding,content2_embedding,content1_embedding_content2_embedding_cosine_similarity
0,PC:,yeah let's try that one,"[yeah, let, try, that, one]","[yeah, let, try, that, one]","[(yeah, NN), (let, VBD), (us, PRP), (try, VB),...","[(yeah, NNS), (let, VBP), (u, JJ), (try, VB), ...","[(yeah, JJ), (let, VB), (us, PRP), (try, VB), ...","[(yeah, JJ), (let, VB), (u, FW), (try, VBP), (...",ASU-T10_ExpBlock1-Oneatatime.txt,yeah let's try that one,...,PC: PB:,"[0.7252197, 0.021484375, 0.5751953, 0.9995117,...","[0.1550293, -0.0048828125, 0.12451172, 0.33203...","[0.7252197, 0.021484375, 0.5751953, 0.9995117,...","[0.1550293, -0.0048828125, 0.12451172, 0.33203...",0.615227,0.615227,"[[0.48487458, -0.1717712, 0.13616683, 0.099701...","[[0.14021963, -0.39036727, 0.06445535, 0.12004...",0.475257
1,PB:,this one,"[this, one]","[this, one]","[(this, DT), (one, NN)]","[(this, DT), (one, NN)]","[(this, DT), (one, CD)]","[(this, DT), (one, CD)]",ASU-T10_ExpBlock1-Oneatatime.txt,this one,...,PB: PA:,"[0.1550293, -0.0048828125, 0.12451172, 0.33203...","[0.3140869, -0.12219238, 0.32458496, 0.9628906...","[0.1550293, -0.0048828125, 0.12451172, 0.33203...","[0.19104004, -0.13500977, 0.30517578, 0.732421...",0.622802,0.643317,"[[0.14021963, -0.39036727, 0.06445535, 0.12004...","[[0.07919585, -0.221765, -0.078900896, 0.17606...",0.448198
2,PA:,yeah that one doesn't look too bad,"[yeah, that, one, not, look]","[yeah, that, one, do, not, look]","[(yeah, NN), (that, WDT), (one, CD), (does, VB...","[(yeah, NN), (that, WDT), (one, CD), (do, VBP)...","[(yeah, NN), (that, IN), (one, CD), (does, VBZ...","[(yeah, NN), (that, IN), (one, CD), (do, VBP),...",ASU-T10_ExpBlock1-Oneatatime.txt,yeah that one doesn't look too bad,...,PA: PB:,"[0.3140869, -0.12219238, 0.32458496, 0.9628906...","[0.06958008, -0.16137695, 0.10253906, 0.278808...","[0.19104004, -0.13500977, 0.30517578, 0.732421...","[0.11230469, 0.018310547, 0.07714844, 0.118652...",0.559877,0.637096,"[[0.07919585, -0.221765, -0.078900896, 0.17606...","[[0.122354224, 0.12566912, -0.28166613, 0.2028...",0.459324
3,PB:,dropped something,[something],"[drop, something]","[(dropped, VBD), (something, NN)]","[(drop, NN), (something, NN)]","[(dropped, VBD), (something, NN)]","[(drop, NN), (something, NN)]",ASU-T10_ExpBlock1-Oneatatime.txt,dropped something,...,PB: PA:,"[0.06958008, -0.16137695, 0.10253906, 0.278808...","[0.16003418, 0.18640137, 0.17085266, 0.4030761...","[0.11230469, 0.018310547, 0.07714844, 0.118652...","[0.16003418, 0.18640137, 0.17085266, 0.4030761...",0.451745,0.521942,"[[0.122354224, 0.12566912, -0.28166613, 0.2028...","[[-0.08179701, 0.26122114, 0.5916559, 0.099716...",0.399607
4,PA:,i feel like that's the solution to all of these,"[like, that, the, all]","[like, that, the, all]","[(i, JJ), (feel, VBP), (like, IN), (that, DT),...","[(i, JJ), (feel, VBP), (like, IN), (that, DT),...","[(i, LS), (feel, VB), (like, IN), (that, DT), ...","[(i, LS), (feel, VB), (like, IN), (that, DT), ...",ASU-T10_ExpBlock1-Oneatatime.txt,i feel like that's the solution to all of these,...,PA: PB:,"[0.16003418, 0.18640137, 0.17085266, 0.4030761...","[0.70703125, 0.4978943, 0.14389038, 1.086853, ...","[0.16003418, 0.18640137, 0.17085266, 0.4030761...","[0.70703125, 0.4978943, 0.14389038, 1.086853, ...",0.756315,0.756315,"[[-0.08179701, 0.26122114, 0.5916559, 0.099716...","[[0.17517856, -0.067751534, 0.42410928, 0.1082...",0.566953